/*
-- Query: SELECT * FROM player_name JOIN gameday_performance ON player_name.player_number = gameday_performance.player_number
LIMIT 0, 1000

-- Date: 2021-08-28 19:17
*/
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (4,'anthony_walker','LB',185,26,'NW',5,4,0,0,0,2,10,1,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (6,'baker_mayfield','QB',186,26,'Oklahoma',4,6,20,3,0,0,0,0,2);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (11,'donovan_peoples_jones','WR',187,22,'Michigan',2,11,0,0,3,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (13,'odell_beckham_jr','WR',186,28,'LSU',8,13,0,0,9,0,0,0,2);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (20,'greg_newsome_ii','CB',182,21,'NW',0,20,0,0,0,0,10,1,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (21,'denzel_ward','CB',180,24,'OSU',4,21,0,0,0,1,25,5,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (24,'nick_chubb','RB',181,25,'Georgia',4,24,0,10,1,0,0,0,1);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (27,'kareem_hunt','RB',191,26,'Toledo',5,27,0,4,3,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (33,'rodney_harrison_jr','S',190,24,'Alabama',4,33,0,0,0,3,17,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (43,'john_johnson_iii','S',189,25,'BC',5,43,0,0,0,1,11,3,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (44,'sione_takitaki','LB',196,26,'BYU',3,44,0,0,0,3,30,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (51,'mack_wilson','LB',186,23,'Alabama',3,51,0,0,0,1,36,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (80,'jarvis_laundry','WR',186,28,'LSU',8,80,1,2,7,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (81,'austin_hooper','TE',198,26,'Stanford',6,81,0,0,3,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (82,'rashard_higgins','WR',196,26,'CSU',6,82,0,0,4,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (85,'david_njoku','TE',193,25,'Miami',5,85,0,0,2,0,0,0,2);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (88,'harrison_bryant','TE',196,23,'FAU',2,88,0,0,0,0,0,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (90,'jadeveon_clowney','DE',196,28,'S.Carolina',8,90,0,0,0,8,20,0,0);
INSERT INTO `` (`player_number`,`player_name`,`position`,`height`,`age`,`college`,`years_of_experience`,`player_number`,`td_pass`,`td_run`,`td_catch`,`sacks`,`tackles`,`def_turnover`,`off_turnover`) VALUES (95,'myles_garrett','DE',193,25,'TAMU',5,95,0,0,0,17,45,0,0);
